version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: personal_beauty
    environment:
      POSTGRES_DB: personal_beauty
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    ports:
      - '5432:5432'

  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - '27017:27017'
